# Generated by Django 3.2.6 on 2021-08-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dataRegister', models.DateTimeField(auto_now_add=True)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=1)),
                ('menu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.TextField()),
                ('dataRegister', models.DateTimeField(auto_now_add=True)),
                ('votaingDate', models.DateTimeField()),
            ],
        ),
    ]
