# Generated by Django 3.2.6 on 2021-08-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_rename_menu_restaurant_menusegunda'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menuQuarta',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menuQuinta',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menuSexta',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menuTerça',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
