# Generated by Django 3.2.6 on 2021-08-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_auto_20210820_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='stars',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
