# Generated by Django 3.2.6 on 2021-08-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_alter_restaurant_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='votaingDate',
            field=models.DateTimeField(default=''),
        ),
    ]
