# Generated by Django 3.2.6 on 2021-08-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_alter_user_votaingdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='menuTerça',
            new_name='menuTerca',
        ),
    ]
