# Generated by Django 3.2.6 on 2021-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0006_rename_menuterça_restaurant_menuterca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='votaingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
