# Generated by Django 3.2.6 on 2021-08-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0007_alter_user_votaingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='dataRegister',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menuQuarta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menuQuinta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menuSegunda',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menuSexta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menuTerca',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
