# Generated by Django 3.2.6 on 2021-08-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0008_auto_20210824_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='votaingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
