# Generated by Django 3.2.6 on 2021-08-25 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0009_auto_20210825_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='dataRegister',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
